---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: triviabot-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/rancher/trivia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triviabot-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
