name: cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Registry login
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: podman login https://docker.pkg.github.com -u ${username} -p ${password}

    - name: Build image
      run: podman build . -t docker.pkg.github.com/jbpratt/triviabot/triviabot:latest

    - name: Publish image
      run: podman push docker.pkg.github.com/jbpratt/triviabot/triviabot:latest
