name: CI - triviabot

on:
  push:
    branches: [ main ]
    paths:
      - 'cmd/triviabot/*'
      - 'internal/trivia*'
      - 'internal/bot/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'cmd/triviabot/*'
      - 'internal/trivia*'
      - 'internal/bot/*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build triviabot
      run: go build -v ./cmd/triviabot
