name: CD - triviabot

on:
  push:
    paths:
      - 'cmd/triviabot/*'
      - 'internal/trivia/*'
      - 'internal/triviabot/*'
      - 'internal/bot/*'
    branches: [ main ]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Registry login
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: podman login ghcr.io -u ${username} -p ${password}

    - name: Build images
      run: |
        podman build --build-arg BOT=triviabot -f Dockerfile -t ghcr.io/jbpratt/triviabot:latest
        podman build --build-arg BOT=triviabot -f arm64.Dockerfile -t ghcr.io/jbpratt/triviabot:arm

    - name: Publish image
      run: |
        podman push ghcr.io/jbpratt/triviabot:latest
        podman push ghcr.io/jbpratt/triviabot:arm
