name: CD - triviabot

on:
  push:
    paths:
      - 'cmd/triviabot/*'
      - 'internal/trivia*'
      - 'internal/bot/*'
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Registry login
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: podman login ghcr.io -u ${username} -p ${password}

    - name: Build image
      run: podman build -f triviabot.Dockerfile -t ghcr.io/jbpratt/triviabot:latest

    - name: Publish image
      run: podman push ghcr.io/jbpratt/triviabot:latest
